### ISSUE TITLE
www.libspf2.org is not resolved

### ISSUE THREAD

**Issue by AndreyMZ** [shevek/libspf2#50]
### Problem description

The website www.libspf2.org referenced on [the GitHub page](https://github.com/shevek/libspf2) does not work.

```
$ host www.libspf2.org
Host www.libspf2.org not found: 5(REFUSED)
```

### Possible solution 1

Delete the reference from the GitHub page.

### Possible solution 2

Revive the website.

**Comment by Kidounet** [comment]
https://www.libspf2.org/ is used in lot of distro but don't work anymore
https://www.libspf2.net/ steel exists, but don't know if is official (1.2.10)
https://www.openspf.org/ in code don't work too ...
vulnerabilities, bugs, test-chain ko, CVE, ... but in whois databases all 3 domain's name renew in 2024

is this project steel active ???

**Comment by Kidounet** [comment]
just see one commit on may for change http://www.libsrs2.org/ to http://www.libsrs2.net in libsrs2 project. behaps just overbooked ?
nice project and hope see devs soon

**Comment by shevek** [comment]
Thank you, this is resolved. I don't control the registry for the .org domain, so I switched everything to .net and it is official. The github page and I think all the READMEs and site links are updated.

**Comment by Neustradamus** [comment]
@shevek: Several tickets about the website.

Linked to:
- https://github.com/shevek/libspf2/issues/53
- https://github.com/shevek/libspf2/issues/50
- https://github.com/shevek/libspf2/issues/40
- https://github.com/shevek/libspf2/issues/33
